base_input_topic: "/usb_cam/image_raw"
face_detected_image_topic: "/face_detector/raw_image"
haar_file_face: "/home/yago/opencv/data/haarcascades/haarcascade_frontalface_alt.xml"
face_tracking: 1
display_original_image: 0
display_tracking_image: 1
